defaults: &defaults
  default_url_options:
    host: 1clickanalytics.ru
    port: 80

  app:
    title: 1ClickAnalytics

development:
  <<: *defaults
  # tld_length: 2
  default_url_options:
    host: 3009.vkontraste.ru
    port: 80

test:
  <<: *defaults

production:
  <<: *defaults
